name: All Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install iverilog
        python -m pip install --upgrade pip
        pip install cocotb-test
        sudo pip install cocotb-test
        pip install pipenv
        pipenv install
        pipenv install --dev
    - name: Test with pytest
      run: |
        pipenv run SIM=icarus pytest
