name: All Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudo pip install pipenv
        sudo pipenv install
        sudo pipenv install --dev
        sudo apt-get install iverilog
    - name: Test with pytest
      run: |
        sudo pipenv run pytest
